contact:
    resource: "@ContactBundle/Resources/config/routing.xml"
    prefix:   /

cms:
    resource: "@CmsBundle/Resources/config/routing.xml"
    prefix:   /

offer:
    resource: "@OfferBundle/Resources/config/routing.xml"
    prefix:   /

newsletter:
    resource: "@NewsletterBundle/Resources/config/routing.xml"
    prefix:   /

front:
    resource: "@FrontBundle/Resources/config/routing.xml"
    prefix:   /

main:
    resource: "@MainBundle/Resources/config/routing.xml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
