newsletter:
    resource: "@NewsletterBundle/Resources/config/routing.xml"
    prefix:   /

front:
    resource: "@FrontBundle/Resources/config/routing.xml"
    prefix:   /

main:
    resource: "@MainBundle/Resources/config/routing.xml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
